// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JakeServer.Migrations
{
    [DbContext(typeof(MindGoblinDbContext))]
    [Migration("20251023044856_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PongGameLobby", b =>
                {
                    b.Property<string>("LobbyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChallengerConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LobbyName")
                        .HasColumnType("TEXT");

                    b.HasKey("LobbyId");

                    b.ToTable("PongGameLobbies");
                });

            modelBuilder.Entity("TetrisScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Player")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TetrisScores");
                });
#pragma warning restore 612, 618
        }
    }
}
