// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JakeServer.Migrations
{
    [DbContext(typeof(JakeServerDbContext))]
    [Migration("20260213033000_AddClinkbitsCurrency")]
    partial class AddClinkbitsCurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ClinkbitTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "CreatedUtc");

                    b.ToTable("ClinkbitTransactions");
                });

            modelBuilder.Entity("EuchreGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EuchreGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamAScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamBScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WinnerTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EuchreGroupId");

                    b.ToTable("EuchreGames");
                });

            modelBuilder.Entity("EuchreGameParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EuchreGameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EuchrePlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EuchreGameId", "EuchrePlayerId")
                        .IsUnique();

                    b.HasIndex("EuchrePlayerId");

                    b.ToTable("EuchreGameParticipants");
                });

            modelBuilder.Entity("EuchreGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("EuchreGroups");
                });

            modelBuilder.Entity("EuchreGroupEditor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EuchreGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EuchreGroupId", "UserAccountId")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("EuchreGroupEditors");
                });

            modelBuilder.Entity("EuchrePlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EuchreGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EuchreGroupId", "Name")
                        .IsUnique();

                    b.ToTable("EuchrePlayers");
                });

            modelBuilder.Entity("PongGameLobby", b =>
                {
                    b.Property<string>("LobbyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChallengerConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LobbyName")
                        .HasColumnType("TEXT");

                    b.HasKey("LobbyId");

                    b.ToTable("PongGameLobbies");
                });

            modelBuilder.Entity("TetrisScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Player")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TetrisScores");
                });

            modelBuilder.Entity("UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinkbitsBalance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClinkbitsUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLoginUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("ClinkbitTransaction", b =>
                {
                    b.HasOne("UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("EuchreGame", b =>
                {
                    b.HasOne("UserAccount", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EuchreGroup", "EuchreGroup")
                        .WithMany("Games")
                        .HasForeignKey("EuchreGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("EuchreGroup");
                });

            modelBuilder.Entity("EuchreGameParticipant", b =>
                {
                    b.HasOne("EuchreGame", "EuchreGame")
                        .WithMany("Participants")
                        .HasForeignKey("EuchreGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EuchrePlayer", "EuchrePlayer")
                        .WithMany("GameParticipants")
                        .HasForeignKey("EuchrePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EuchreGame");

                    b.Navigation("EuchrePlayer");
                });

            modelBuilder.Entity("EuchreGroup", b =>
                {
                    b.HasOne("UserAccount", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("EuchreGroupEditor", b =>
                {
                    b.HasOne("EuchreGroup", "EuchreGroup")
                        .WithMany("Editors")
                        .HasForeignKey("EuchreGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EuchreGroup");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("EuchrePlayer", b =>
                {
                    b.HasOne("EuchreGroup", "EuchreGroup")
                        .WithMany("Players")
                        .HasForeignKey("EuchreGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EuchreGroup");
                });

            modelBuilder.Entity("EuchreGame", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("EuchreGroup", b =>
                {
                    b.Navigation("Editors");

                    b.Navigation("Games");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("EuchrePlayer", b =>
                {
                    b.Navigation("GameParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
